
# 목표
자바의 예외 처리에 대해 학습하세요.
<br>

## 학습할 것 (필수)
- 자바에서 예외 처리 방법 (try, catch, throw, throws, finally)
- 자바가 제공하는 예외 계층 구조
- Exception과 Error의 차이는?
- RuntimeException과 RE가 아닌 것의 차이는?
- 커스텀한 예외 만드는 방법
<br>


### 자바에서 예외 처리 방법 (try, catch, throw, throws, finally)
---
  **예외(Exception)**
  - 개발자가 예측 가능한 상황.
  - 예측 가능하기 때문에 코드로 복구 가능. (예외 처리)
<br>

  ### 예외 복구 (try ~ catch)
    예측 가능한 오류를 개발자가 사전에 처리 방법을 구현. (일종의 보험 기능)
  - `try` 문에는 예외 발생이 예측되는 코드가, `catch` 문에는 예외타입과 예외 발생 시 처리 문이 작성된다.
  - `catch` 문은 `else if` 처럼 여러 개의 `catch` 문 작성 가능.
  - `finally` 문은 예외 발생과 관련없이 실행될 코드를 작성.
<br>

  **형태**
  ```java
  try {
    // 예외 발생 가능 코드
  }
  catch(예외타입) {
    // 예외 발생 시 실행 코드
  }
  finally {
    // 예외 발생과 관련없이 실행될 코드
  }
  ```
  - `try` 문에서 **예외가 발생할 경우** 예외타입에 맞는 `catch` 문을 실행하고 `finally` 문 실행.
  - `try` 문에서 **예외가 발생하지 않을 경우** `catch` 문을 생략하고 `finally` 문으로 분기 및 실행.

  **For example**
  ```java
  int A = 10;
  int Z = 0;
  int R = 0;

  try {
    R = A/Z;
  } catch(ArthmeticException e) {
    e.printStackTrace();
    System.out.println("Exception 발생 " + e.getMessage());
  } finally {
    System.out.println(A/(Z+1));
  }
  ```
  > **printStackTrace()** : 예외 발생 위치와 내용 출력. <br>
  > **getMessage()** : 예외 내용 반환.
  ```java
  java.lang.ArithmeticException: / by zero
	  at com.study.Test.main(Test.java:7)
  Exception 발생 / by zero
  10
  ```
<br>

  ### 예외 처리 회피 (throws)
    예외가 발생할 경우 현재 메소드를 호출한 곳에 예외 발생 여부를 통보.
  - `throws` 키워드를 메소드명 뒤에 예외타입과 함께 작성.

<br>

  **형태**
  ```java
  접근제어자 반환타입 메소드명 throws 예외타입 {...}
  ```
  **For example**
  ```java
  public class BMI {
    public void bmicheck(int he, int we) throws ArithmeticException {  // ArithmeticException 타입의 예외가 발생할 경우 던지기.
      int bmi = we / he*2;
      System.out.println("BMI는 " + bmi + "입니다.");
    }
  }

  public class Print {
    public static void main(String[] arg) {
      BMI bmi = new BMI();

      try {
        bmi.bmicheck(0, 58);
      } catch(ArithmeticException e) {
        System.out.println("키는 0이 될 수 없습니다.");
      }
    }
  }
  ```
  ```
  키는 0이 될 수 없습니다.    // 0으로 나눗셈을 시도했기 때문에 예외 발생 및 catch 문 실행.
  ```
  - `ArithmeticException` 타입의 예외가 `main`에서 발생했기 때문에 `bmicheck` 메소드는 예외 처리를 자신을 호출한 `main` 메소드로 던져버린다.
  - 그 후, `main` 메소드에서 예외를 처리한다. (try ~catch 문)
<br>

  ### 임의 예외 발생 (throw)
    프로그래머가 임의로 예외를 발생시킬 때 사용.
  - `throw` 키워드와 함께 `new`, `발생시킬 예외`를 작성.

  **형태**
  ```java
  throw new 발생시킬 예외
  ```

  **For example**
  ```java
  try {
    throw new Exception();                // 임의로 예외 발생시킴.
  } catch(Exception e) {
    System.out.println("Exception 발생"); // catch 문 실행.
  }
  ```
  ```
  Exception 발생
  ```
  - 임의로 발생시킨 예외로 `catch` 문 실행.
<br>

> **Why use** <br><br>
> - `throws`와 함께 사용하여 예외를 한 번 더 처리해주기 위함. (분산 처리 효과)
> - 사용의 대표적인 예로, try 문에 여러 실행문을 작성하고 싶은 경우, 먼저 작성된 실행문에 예외가 발생할 경우 catch 문으로 분기하게 된다.
> - 그렇기 때문에 try 문을 분산 작성하여 여러 곳에서 처리한다.
<br>


### 자바가 제공하는 예외 계층 구조
---
  - Java 에서는 오류로 발생할 수 있는 경우의 수를 클래스로 정의하고 있다.
  - Java 오류 부문의 최상위 클래스로 `Throwable`가 존재.
  - `Throwable`의 서브 클래스로 `Error`와 `Exception`이 존재.
  - Java 의 모든 클래스와 같이 최상위 조상으로 `Object` 클래스가 존재.
<br>

  <p align="center"><img src="https://github.com/SeungTaeGit/Language/assets/129585999/7cb9cea3-c6ef-49e3-9a15-71b46bbffd0a"></p>
  
  > **Throwable** 클래스를 상속받은 서브 클래스만이 `throws` 키워드를 통해 예외 던지기가 가능.
<br>


### Exception과 Error의 차이는?
---
  - **Java 의 오류**는 `Error`와 `Exception`으로 나뉜다.
<br>

  #### Exception
  - 개발자가 예측 가능한 Java 의 오류.
  - 대다수의 경우 개발자의 실수로 인한 오류 발생.
  - 그렇기 때문에, 예측하기 비교적 쉽고 빠르게 복구 가능.
  - 하위 클래스의 성질에 따라 `checked Exception`과 `unckecked Exception`으로 나뉜다.
  - 복구를 하기 위한 방법으로 `예외 복구`, `예외 처리 회피`, `예외 전환`이 있다.
  <p align="center"><img src="https://github.com/SeungTaeGit/Language/assets/129585999/e4e6cf21-ac9f-43f1-8921-5bd613fb3274"></p>
<br>

  #### Error
  - 프로그램에 비정상적인 상황이 발생한 경우.
  - 프로그래머가 처리 불가능한 오류. (코드에서 복구 불가.)
  - 주로 **JVM**에서 발생.
  - `StackOverflowError`, `OutOfMemoryError` 등이 존재.
  <p align="center"><img src="https://github.com/SeungTaeGit/Language/assets/129585999/ee93d7a2-4a6b-4b39-964e-8bb9df388d5e"></p>
<br>


### RuntimeException과 RE가 아닌 것의 차이는?
---
  - Exception 의 하위 클래스 중 `RuntimeException`과 그 `하위 클래스들`은 모두 `unckecked Exception`이다.
  - `RuntimeException을 제외한 클래스`와 그 `하위 클래스들`은 `checked Exception`이다.

  <p align="center"><img src="https://github.com/SeungTaeGit/Language/assets/129585999/4cbb2a15-f695-4ad2-943f-ce523849231a"></p>
<br>

  ### Unchecked Exception (RuntimeException)
  - 예외 처리를 **강제하지 않는** 예외.
  - `RuntimeException`과 그 `하위 클래스들`로 구성.
  - 컴파일러가 따로 예외 처리를 확인하지 않는다. (실행 시점에 확인.)
  - ex) IOException, SQLException 등
<br>

  ### Checked Exception
  - 예외 처리를 **강제하는** 예외.
  - `RuntimeException을 제외한 클래스`와 그 `하위 클래스들`로 구성.
  - 컴파일러가 예외 처리를 확인. (컴파일 시점에 확인.)
  - ex) ArrayIndexOutOfBoundsException, NullPointerException 등
<br>


### 커스텀한 예외 만드는 방법
---
  - Java 는 기존에 존재하는 예외 클래스 이외에 프로그래머가 예외 클래스를 커스텀하는 것을 지원한다. (프로그래머가 필요에 의해 예외를 추가하는 행위.)
  - `커스텀 예외 클래스`는 예외 부문의 가장 상위 클래스인 `Exception` 클래스를 상속받는다. (필요에 따라 다른 예외 클래스도 상속 가능.)
<br>

  **형태**
  ```java
  class 커스텀예외클래스명 extends Exception {
    커스텀예외클래스명(매개변수 목록) {	// 생성자
      // 구현부
    }
  }
  ```

  **For example**
  ```java
  class SizeException extends Exception {
    private final int Error;

    public SizeException(String message) {
      this(message, 222);			// 생성자 호출
    }

    public SizeException(String message, int Error) {
        super(message);			
        this.Error = Error;
    }

    public int getError() {			// 에러 코드 반환 메소드.
        return Error;
    }
  }
  ```
  - 커스텀 예외 클래스의 `SizeException(String msg)` 생성자를 호출했다고 예를 들 경우,
  - `msg`와 `222`를 매개변수로 `SizeException(String msg, int Error)` 생성자 호출.
  - `super(msg)` 메소드로 **Throwable** 클래스의 `getMessage()`를 통해 메세지를 처리.
  - `getError` 메소드로 에러 코드 반환.

  ```java
  public class RobotException {
    public static void main(String[] args) {
        try {
            checkSize(501);
        } catch (SizeException e) {
            e.printStackTrace();
            System.out.println("ERROR MESSAGE : "+ e.getMessage());
            System.out.println("ERROR CODE : "+ e.getError());
        }
    }

    private static void checkSize(int Size) throws SizeException {
        final int BigestSize = 500;

        if(BigestSize - Size < 0)				// Size가 BigestSize보다 클 경우
            throw new SizeException("Too Big Size");	// message를 매개변수로 객체 생성
    }
  }
  ```
  - 위의 경우 `Size`가 `BigestSize`보다 크기 때문에 커스텀 예외가 발생. (임의 예외 발생(throw))
  - `main` 메소드의 `catch` 문 실행.
  ```java
  com.robotcompany.robot.SizeException Create breakpoint : Too Big Size		// printStackTrace() 호출 및 출력.
    at com.robotcompany.robot.RobotException.checkSize(RobotException.java:16)
    at com.robotcompany.robot.RobotException.main(RobotException.java:4)
  ERROR MESSAGE : Too Big Size
  ERROR CODE : 222
  ```
<br>


___
___
#### REFERENCE
> **예외 처리** : https://kadosholy.tistory.com/106 <br>
> **throw, throws** : https://bvc12.tistory.com/196 <br>
> **예외 계층 구조** : https://reakwon.tistory.com/155 <br>
